#!/bin/bash

if [[ $# -ne 2 ]] ; then
  echo './docker-exec - run a command on a specified ruby version'
  echo 'Usage:'
  echo '  ./docker-exec 2.2.5 rake spec'
  exit 1
fi

ruby_version="$1"
bundled_command="$2"

cp -r /app ..

# Disable strict settings that break chruby
set +o nounset
set +o noglob

source /usr/local/share/chruby/chruby.sh

chruby "$ruby_version"

# Reenable strict settings
set -o nounset
set -o noglob

# Hack to work around sickill/rainbow#44
gem install rake

bundle --path /bundle

bundle exec "$bundled_command"
